# .render.yaml

# 1. Khai báo Web Service để Render biết deploy backend của bạn
services:
  - type: web
    name: thuetool-backend         # Tên bạn đặt cho service
    env: node
    plan: free                     # kế hoạch Free
    region: singapore              # hoặc us, oregon, ...
    repo: erfolgreich225/thuetool-online  # repo trên GitHub của bạn
    branch: main
    buildCommand: "cd backend && npm install && npm run build"
    startCommand: "cd backend && npm run start"
    envVars:                       # biến môi trường
      - key: MONGODB_URI
        fromSecret: MONGODB_URI
      - key: TELEGRAM_BOT_TOKEN
        fromSecret: TELEGRAM_BOT_TOKEN
      - key: TELEGRAM_CHAT_ID
        fromSecret: TELEGRAM_CHAT_ID

cron_jobs:
  - name: keep-alive-healthz
    type: http
    schedule: "*/5 * * * *"
    url: "https://thuetool-online.onrender.com/healthz"
    method: GET
    env: node

